[workspace]
[package]
version = "0.1.0"
name = "keccak-precompile"
edition = "2021"

[dependencies]
#zkm-runtime = { git = "https://github.com/zkMIPS/zkm", package = "zkm-runtime" }
zkm-runtime = { path = "../../../../runtime/entrypoint" }
