[workspace]
[package]
version = "0.1.0"
name = "sha2-bench"
edition = "2021"

[dependencies]
zkm-runtime = { path = "../../runtime/entrypoint" }
sha2 = { version = "0.10.8", default-features = false }
